- name: Installing and Configuring Ticket Monster Java App
  hosts: all
  gather_facts: True
  become: yes
  remote_user: centos
  become_method: sudo
  
  roles:
     - common
     - jboss-standalone
     - java-app
