################################################################################################
# Creating an Entire VPC Environment in AWS                                                    #
#                                                                                              #
# By Robert J. Calva - Red Hat LATAM - 2016                                                    #
#                                                                                              #
# NOTE: just set the aws_region, aws_zone, name_zone, attendee, aws_keypair and                #
# volume_type variables as you wish!                                                           #
#                                                                                              #
# IMPORTANT: regarding storage_type information, please take a look at this link:              #
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html                       #
#                                                                                              #
# Variable examples:                                                                           #
#                                                                                              #
# aws_region could be: sa-east-1 or us-east-1                                                  #
# aws_zone could be: sa-east-1a, sa-east-1b, us-east-1a, us-east-1b                            #
# name_zone could be: example.com                                                              #
# volume_type could be: standard or gp2                                                        #
#                                                                                              #
# Enjoy!                                                                                       #
################################################################################################
- name: Create an Entire VPC Environment in AWS
  hosts: localhost
  gather_facts: True
  connection: local
  
  tasks:
  - name: Create the VPC in AWS {{ aws_region }}
    ec2_vpc:
        state: present
        cidr_block: 192.168.0.0/16
        resource_tags: { "Name":"Workshop VPC {{ attendee }}" }
        subnets:
          - cidr: 192.168.1.0/24
            az: "{{ aws_zone }}"
            resource_tags: { "Name":"workshop-private-subnet" }
        internet_gateway: True
        route_tables:
          - subnets:
              - 192.168.1.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        region: "{{ aws_region }}"
        wait: yes
    register: vpc

  - set_fact: vpc_id={{ vpc.vpc_id }}
  - set_fact: subnet_id={{ vpc.subnets[0].id }}

  - name: Create an AWS Security Group for our Workshop
    ec2_group:
      name: "aws-workshop-sec-group"
      region: "{{ aws_region }}"
      description: Workshop Security Group
      vpc_id: "{{ vpc_id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
    register: aws_workshop_sec_group

  - name: Creating an AWS Instance in our VPC 
    ec2:
      key_name: "{{ aws_keypair }}"
      group: aws-workshop-sec-group
      instance_type: t2.micro
      #image: ami-b63769a1
      image: ami-eea2ab95
      wait: yes
      wait_timeout: 500
      volumes:
      - device_name: /dev/sda1
        volume_type: "{{ volume_type }}"
        volume_size: 40
        delete_on_termination: true
#      instance_initiated_shutdown_behavior: stop
      termination_protection: no
      instance_tags:
        Name: "{{ instance_name }}"
      exact_count: 1
      count_tag:
        Name: "{{ instance_name }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: "{{ subnet_id }}"
      zone: "{{ aws_zone }}"
      assign_public_ip: yes
    register: ec2
