---
- name: Create an Instance in AWS
  hosts: localhost
  gather_facts: True
  connection: local
  
  tasks:
  - name: Creating an AWS Instance in our VPC 
    ec2:
      key_name: "{{ aws_keypair }}"
      group: aws-workshop-sec-group
      instance_type: t2.micro
      image: ami-ae7bfdb8
      wait: yes
      wait_timeout: 500
      volumes:
      - device_name: /dev/sda1
        volume_type: "{{ volume_type }}"
        volume_size: 10
        delete_on_termination: true
      termination_protection: no
      instance_tags:
        Name: "{{ instance_name }}"
      count: "{{ instance_count }}"
      count_tag:
        Name: "{{ instance_name }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: "{{ subnet_id }}"
      zone: "{{ aws_zone }}"
      assign_public_ip: yes
    register: ec2
    
  #- debug: var=ec2
  
  - ec2_facts:
  - local_action:
      module: ec2_elb
      ec2_region: "{{ region }}"
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "ticketmonster"
      state: present
      wait: yes
      wait_timeout: 60
    become: false
    ignore_errors: yes
  
  - set_stats:
      data:
        ec2_public_ip: "{{ ec2.instances[0].public_ip }}"
        ec2_dns_name: "{{ ec2.instances[0].public_dns_name }}"
      per_host: no
