- name: Installing and Configuring Ticket Monster Java App
  hosts: all
  gather_facts: True
  become: yes
  remote_user: ec2-user
  become_method: sudo
  
  roles:
     - common
     - jboss-standalone
     - java-app
