---
- name: Install software into AWS Instance
  hosts: localhost
  gather_facts: True
  connection: local
  
  tasks:
    - name: Add new instance to host group
      add_host: hostname={{ ec2_public_ip }} groupname=linux_launched

    - name: Wait for SSH to come up
      wait_for: host={{ ec2_dns_name }} port=22 delay=60 timeout=320 state=started


- name: Installing and Configuring Ticket Monster Java App
  hosts: linux_launched
  gather_facts: True
  become: yes
  become_method: sudo
  
  roles:
     - common
     - jboss-standalone
     - java-app
